#!/bin/bash
# USAGE: start|status
#
case "$1" in
start)
echo "Starting Home Controller."
nohup /opt/home-controller/home-controller.py &
;;
status)
# Check to see if the process is running
ps aux|grep -i home-controller
;;

*)
echo “Home Controller Web Portal Service”
echo $”Usage: $0 {start|status}”
exit 1
esac
exit 0
