#!/bin/bash
# USAGE: start|status|stop
#

do_start () {
	echo "Starting Home Controller."
	nohup python /opt/home-controller/home-controller.py &
}

case "$1" in
start)
	do_start
;;
status)
	# Check to see if the process is running
	ps aux|grep -i home-controller
;;
stop)
	pkill -f home-controller.py
;;
*)
	echo “Home Controller Web Portal Service”
	echo $”Usage: $0 {start|status|stop}”
	exit 1
esac
exit 0
